### ISSUE TITLE
Add info for previous versions

### ISSUE THREAD

**Issue by nahir31** [jdhitsolutions/PSFunctionInfo#5]
The idea of adding version info is indeed super useful and very well done 👍 

Here are my two cents.. On promoting a function version it would be helpful to support adding info of when, why and by who the version was changed. 

Example:

```
Version 1.0.2 Adding support for zipped files (2021-04-22 Bob)
Version 1.0.1 Adding details on the Verbose output (2021-04-20 Alice)
Version 1.0.0 Initial version (2021-04-18 Jeff)
```

This data should be set as an AllVersion property: an array of objects each with 4 props: 
VerNum, ChangeReason, Date, Author

**Comment by jdhitsolutions** [comment]
What you are talking about is a changelog. I'm not so sure I want to include that as it then makes the metadata block inconsistent across files. This is where using change management like git comes into the picture. If you want to keep change history inside the file, I would do it in a separate comment block at the end of the file.

**Comment by nahir31** [comment]
Version control system like git are great but not everyone that writes Powershell also use such system. 

In addition:

1. In most cases a single git commit consists of several files, but the message is one per commit. So it’s not easy to isolate why a specific function was changed. 

2. In order to see the change log the console is not ideal. For a useful compare you usually need some IDE with a history feature.   

3. Not every function is created within a git worktree, even by people that use git. 

4. Even when the author uses git, the consumer might not. 

Few years ago I started to add such changes info to the critical functions and scripts. It is later very handy to compare two versions using tools like BeyondCompare and see the declared reason for the change on the same view with the actual code changes. With your idea these compares can be taken to the next level by getting the info as objects. 

Of course it could be on s separate comment block as per your suggestion.

**Comment by jdhitsolutions** [comment]
I think we agree that changelog information doesn't belong with command metadata. If you want to keep it as part of the file, I agree that a separate comment block is the best approach. Everyone has different changelog ideas and requirements so I'm not about to decide what people should use.

**Comment by nahir31** [comment]
Totally understood and many thanks for taking the time to respond!
